name = "MDResidue"
uuid = "b485d239-1e83-42ca-a4ac-00f7fb828a29"
authors = ["gang chen"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
